name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }} 
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo build --verbose
        run: cargo test --verbose
  darwin:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo build --verbose
        run: cargo test --verbose
  deploy:
    needs: [test]

