name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: cargo build --verbose
  #     - name: Run tests
  #       run: cargo test --verbose

  aarch-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [aarch64, armv7]
    name: Build/Test for aarch64/armv7
    steps:
      - uses: actions/checkout@v4
      - uses: monorepo/setup-rust@v1
      - uses: uraimo/run-on-arch-action@v3
        name: Run commands
        with:
          arch: armv7
          distro: ubuntu24.04
          githubToken: ${{ github.token }}

          run: |
            rustup target add ${{ matrix.target }}
            cargo install cross --git https://github.com/cross-rs/cross
            run: cross build --verbose --target ${{ matrix.target }}
            run: cross test --verbose --target ${{ matrix.target }}
