name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: cargo build --verbose
  #     - name: Run tests
  #       run: cargo test --verbose

  aarch-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]
    name: Build/Test for ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: cross build --verbose --target ${{ matrix.target }}
      - name: Run tests
        run: cross test --verbose --target ${{ matrix.target }}
